version: '3.4'
name: "lena_webappcase"
services:
  development.mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "DEVELOPMENT_LENA_MSSQL"
    restart: always
    ports: 
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "devPassw0rd!"