// <auto-generated />
using System;
using LENA.WebAppCase.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LENA.WebAppCase.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LENA.WebAppCase.Core.Model.Field", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Formid")
                        .HasColumnType("int");

                    b.Property<string>("dataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("required")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("Formid");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("LENA.WebAppCase.Core.Model.Form", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("LENA.WebAppCase.Core.Model.Field", b =>
                {
                    b.HasOne("LENA.WebAppCase.Core.Model.Form", null)
                        .WithMany("fields")
                        .HasForeignKey("Formid");
                });

            modelBuilder.Entity("LENA.WebAppCase.Core.Model.Form", b =>
                {
                    b.Navigation("fields");
                });
#pragma warning restore 612, 618
        }
    }
}
